server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://localhost:8081/api/v1/users
          predicates:
            - Path=/api/v1/users

        - id: userCmdApi-UpdateUser
          uri: http://localhost:8081/api/v1/users/**
          predicates:
            - Path=/api/v1/users/
            - Method=PUT

        - id: userCmdApi-RemoveUser
          uri: http://localhost:8081/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**
            - Method=DELETE

        - id: userQueryApi-findAll
          uri: http://localhost:8082/api/v1/users
          predicates:
            - Path=/api/v1/users

        - id: userQueryApi-findByParam
          uri: http://localhost:8082/api/v1/users/**
          predicates:
            - Path=/api/v1/users/**

        - id: account-openAccount
          uri: http://localhost:9091/api/v1/accounts
          predicates:
            - Path=/api/v1/accounts

        - id: account-operationFundsAccount
          uri: http://localhost:9091/api/v1/accounts/**
          predicates:
            - Path=/api/v1/accounts/**
            - Method=PUT,DELETE

        - id: account- getAccounts
          uri: http://localhost:9092/api/v1/accounts/**
          predicates:
            - Path=/api/v1/accounts/**
            - Method=GET

