server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
      username: admin
      password: admin
      authentication-database: admin

security:
  oauth2:
    authorization:
      jwt:
        key-value: springbankSigningKey
