server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank-account
      username: admin
      password: admin
      authentication-database: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: admin
    password: admin
