server:
  port: 8081

spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: bank
#      username: admin
#      password: admin
      uri: mongodb://admin:admin@127.0.0.1:27017/bank?authSource=admin

security:
  oauth2:
    authorization:
      jwt:
        key-value: springbankSigningKey


